### ISSUE TITLE
ValueError: tile cannot extend outside image

### ISSUE THREAD

**Issue by 1660961935** [bearsprogrammer/real-time-deep-face-recognition#35]
Error while Running Make_aligndata_git.py
This error will occur only when running some image. Delete this image can continue running.

Traceback (most recent call last):
  File "D:/Python/Python project/real-time-deep-face-recognition-master/Make_aligndata_git.py", line 96, in <module>
    scaled_temp = misc.imresize(cropped_temp, (image_size, image_size), interp='bilinear')
  File "D:\Python\Anaconda3\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "D:\Python\Anaconda3\lib\site-packages\scipy\misc\pilutil.py", line 555, in imresize
    im = toimage(arr, mode=mode)
  File "D:\Python\Anaconda3\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "D:\Python\Anaconda3\lib\site-packages\scipy\misc\pilutil.py", line 408, in toimage
    image = Image.frombytes(mode, shape, strdata)
  File "D:\Python\Anaconda3\lib\site-packages\PIL\Image.py", line 2387, in frombytes
    im.frombytes(data, decoder_name, args)
  File "D:\Python\Anaconda3\lib\site-packages\PIL\Image.py", line 797, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image

**Comment by 1660961935** [comment]
I think this image don't detect face,because cropped_temp=[]
