### ISSUE TITLE
Error while running Make_aligndata_git.py

### ISSUE THREAD

**Issue by elnasdgreat** [bearsprogrammer/real-time-deep-face-recognition#8]
![1](https://user-images.githubusercontent.com/19590512/31310402-23299ec4-abca-11e7-94b1-ea10ab19c2b1.jpg)
Thank you for the code!! :D 
I have installed all the requirements through Anaconda
Whenever I try to run the Make_aligndata_git.py, it shows me this error.

Traceback (most recent call last):
  File "F:\Temp\real-time-deep-face-recognition-master\Make_aligndata_git.py", line 5, in <module>
    from scipy import misc
  File "C:\Users\ElnasD'greaT\Anaconda3\envs\tensorflow\lib\site-packages\scipy\__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "C:\Users\ElnasD'greaT\Anaconda3\envs\tensorflow\lib\site-packages\numpy\__init__.py", line 126, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Users\ElnasD'greaT\Anaconda3\envs\tensorflow\lib\site-packages\numpy\__config__.py", line 5
    blas_mkl_info={'library_dirs': ['C:/Users/ElnasD'greaT/Anaconda3/envs/tensorflow\\Library\\lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'libraries': ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll'], 'include_dirs': ['C:/Users/ElnasD'greaT/Anaconda3/envs/tensorflow\\Library\\include']}
                                                         ^
SyntaxError: invalid syntax

**Comment by elnasdgreat** [comment]
Solved it, my pc name wasn't escaped, so I edited the __config__.py

**Comment by mpena2099** [comment]
@elnasdgreat , please close this issue.
